spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex
    username: root
    password: root123

  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
